# -*- coding: utf-8 -*-
T0 = [
("00 METHOD · The only reliable way to do a transition question","COVER THE CHOICES. Read the sentence before and the sentence after, then say the relationship out loud in your own words: 'this is an example of that', 'this contradicts that', 'this is the result of that'. | ONLY THEN look at the four options and pick the one that matches your phrase. | Reading the choices first is what makes these questions hard."),
("00 METHOD · The four relationships that cover almost everything","1 CONTRAST (but). 2 CAUSE-EFFECT (so). 3 ADDITION (and). 4 EXAMPLE or SPECIFICATION (like). | Decide which of these four it is BEFORE reading the options. | Most wrong answers come from picking the right family's wrong member, or from never committing to a family."),
("00 METHOD · Direction first, flavor second","First ask only one thing: does the second sentence AGREE with the first or PUSH AGAINST it? | That question alone eliminates two choices, because the test always offers both directions. | Then choose within the surviving pair."),
("00 METHOD · The four choices are never four synonyms","The test gives you one option from each relationship family, so exactly one direction fits. | If two options look like synonyms to you (for example / for instance), NEITHER is likely right, because the test avoids having two defensible answers. | Treat a synonym pair as a hint to look at the other two."),
("00 METHOD · Never pick the word that sounds smartest","Nevertheless, moreover, furthermore and in other words feel academic, and that is exactly why they are the most common traps. | The credited answer is usually the plainest one: however, as a result, specifically."),
("00 METHOD · Detail is not the same as an example","Students reach for 'for example' whenever the next sentence contains specifics. | But specifics that SHARPEN the same point call for 'specifically'. Only a standalone INSTANCE of a general rule takes 'for example'. | This one distinction is the most valuable idea in this deck."),
("00 METHOD · Look wider than one sentence","Sometimes the relationship is to the whole paragraph, not just the sentence immediately before. | If nothing fits, widen your view by one sentence before you guess."),
("01 TRAPS · The five most over-chosen wrong answers","IN OTHER WORDS, SIMILARLY, NEVERTHELESS, LIKEWISE and FOR EXAMPLE are offered constantly and are right far less often than students assume. | Each one demands a strict condition (see their own cards). | Before picking any of these five, say out loud what makes it required, not merely acceptable."),
("01 TRAPS · Words that are almost never the answer","REGARDLESS, IN CONCLUSION, FURTHERMORE, FIRSTLY, SECONDLY, LASTLY, IN SUM, IN SUMMARY. | They are either wrong register for the test or they need a whole finished essay around them. | Treat them as strong warning signs, not absolute rules."),
("01 TRAPS · Why 'in conclusion' can never work","Test passages are EXCERPTS, not complete essays, so nothing inside them is ever wrapping up a full argument. | The same logic rules out in summary, in sum, to conclude and lastly. | Spotting the excerpt structure eliminates an entire family at once."),
("01 TRAPS · The 'for example' vs 'specifically' split","FOR EXAMPLE needs a separate, standalone instance of the general claim. | SPECIFICALLY needs only a sharper version of the SAME claim. | When torn, 'specifically' is the safer bet, because most test sentences refine rather than exemplify."),
("02 REGISTER · The formality range the test prefers","PREFERRED: however, therefore, as a result, in addition, for example, specifically, by contrast. | TOO INFORMAL: besides, what's more, actually, nowadays, second of all. | TOO STILTED: firstly, secondly, in the second place. | Register alone can eliminate two choices."),
]
# (section, transition, function, note, example)
T = [
("03 CONTRAST","however","CONTRAST","The two sentences must genuinely CONFLICT. The strongest and most often correct contrast word.","Most reptiles rely on external heat. ___, a few species can raise their own body temperature while brooding."),
("03 CONTRAST","by contrast","CONTRAST","Two comparable things are set side by side and they DIFFER. Needs two parallel subjects, not just any disagreement.","Desert soils lose nitrogen quickly. ___, wetland soils retain it for decades."),
("03 CONTRAST","in contrast","CONTRAST","Same job as 'by contrast'. Needs two parallel subjects that differ.","Her early paintings are crowded and dark. ___, the later canvases are nearly empty."),
("03 CONTRAST","on the other hand","CONTRAST","Presents a second, opposing side of the SAME issue. Expects a first side to have been given.","Tidal power is highly predictable. ___, it can only be generated in a few coastal locations."),
("03 CONTRAST","conversely","CONTRAST","The relationship is REVERSED, not merely different. One goes up as the other goes down.","Warmer water holds less dissolved oxygen. ___, colder water holds more."),
("03 CONTRAST","instead","CONTRAST","Replaces a rejected option with the actual one. Requires that something was ruled out first.","The team did not drain the pond. ___, they lowered it by half and waited."),
("03 CONTRAST","on the contrary","CONTRAST","Flatly CONTRADICTS a preceding negative or false claim. Needs an explicit claim to deny, which is why it is usually wrong.","The reform did not reduce enrollment. ___, applications rose by a third."),
("03 CONTRAST","rather","CONTRAST","Corrects rather than adds: not X, rather Y. Needs a preceding negation.","The marks are not decorative. ___, they record the depth of each flood."),
("03 CONTRAST","alternatively","ALTERNATIVE","Offers a different possible OPTION or method, not a contradiction.","Researchers can date the layer using pollen. ___, they can measure trapped isotopes."),
("03 CONTRAST","in any case","DISMISSAL","Sets aside what came before as not decisive. Rare as a correct answer.","The exact date is still disputed. ___, the structure predates the harbor."),
("04 CONCESSION","nevertheless","CONCESSION","Admits the previous point, then pushes back anyway. Needs a real concession first, which is why it is so often a trap.","The sample was small and poorly preserved. ___, it remains the only physical evidence from the period."),
("04 CONCESSION","nonetheless","CONCESSION","Identical to 'nevertheless'. Concede, then persist.","Funding was cut twice. ___, the survey finished on schedule."),
("04 CONCESSION","that said","CONCESSION","Conversational concession followed by a qualification. The prior sentence must be something you are partly granting.","The model predicts the last decade well. ___, it fails badly before 1960."),
("04 CONCESSION","still","CONCESSION","Despite that, what follows remains true. Softer than 'nevertheless'.","Critics dismissed the technique for years. ___, she kept refining it."),
("04 CONCESSION","granted","CONCESSION","Explicitly concedes a point before countering it.","___, the instrument drifts in high heat. Its readings are otherwise the most precise available."),
("04 CONCESSION","admittedly","CONCESSION","Concedes a weakness in your own argument.","___, the correlation is weak. It is nevertheless the only pattern that survives every model."),
("04 CONCESSION","though","CONCESSION","Tacks on a qualification. Informal, and rarely correct on the test.","The repair held for a season. It was never meant to be permanent, ___."),
("04 CONCESSION","all the same","CONCESSION","Same as 'nevertheless'. Concede, then hold your position.","The translation loses the rhyme. ___, it captures the argument exactly."),
("04 CONCESSION","even so","CONCESSION","Accepts the prior fact but maintains the conclusion anyway.","The glacier gained mass in two of the years. ___, the overall trend is a steady retreat."),
("04 CONCESSION","regardless","DISMISSAL","Dismisses the previous point as irrelevant. Offered often and almost never credited. Treat as a near-certain distractor.","The permits were filed late. ___, construction began on time."),
("05 CAUSE","as a result","CAUSE-EFFECT","The second sentence is the OUTCOME of the first. One of the most frequently correct transitions.","The dam altered the river's sediment load. ___, the delta began to shrink."),
("05 CAUSE","therefore","CAUSE-EFFECT","A logical conclusion drawn from the prior statement. More deductive than 'as a result'.","Every sample contained the same isotope ratio. ___, they must share a single source."),
("05 CAUSE","thus","CAUSE-EFFECT","Same as 'therefore', more compressed. Often a distractor when the link is not truly causal.","The two curves never intersect. ___, the system has no real solution."),
("05 CAUSE","consequently","CAUSE-EFFECT","Emphasizes that the result FOLLOWED FROM the cause.","The species lost its only pollinator. ___, seed production collapsed within a decade."),
("05 CAUSE","hence","CAUSE-EFFECT","Formal synonym for 'therefore'.","The alloy expands unevenly when heated. ___, it is unsuitable for precision instruments."),
("05 CAUSE","accordingly","CAUSE-EFFECT","Someone ACTED in response to the prior fact. Needs an agent doing something, not just an abstract result.","Early trials showed the dosage was too high. ___, the researchers halved it."),
("05 CAUSE","for this reason","CAUSE-EFFECT","Points explicitly back at a stated cause. Needs a clearly identified reason immediately before.","Basalt weathers far faster than granite. ___, geologists use it to date young lava flows."),
("05 CAUSE","in turn","CAUSE-EFFECT","A chain reaction: A causes B, which then causes C.","Warmer springs advance the insect hatch. This, ___, leaves migrating birds arriving too late to feed."),
("05 CAUSE","as such","CAUSE-EFFECT","Because of the quality just described. Often misused where 'therefore' is wanted.","The manuscript is a working draft. ___, its inconsistencies are expected rather than puzzling."),
("06 EXAMPLE","for example","EXAMPLE","What follows must be a SPECIFIC INSTANCE of the general claim. It is the most common answer choice on the test and usually a distractor, because students pick it whenever the next sentence merely contains a detail.","Some plants recruit insects to defend them. ___, acacias house stinging ants in their hollow thorns."),
("06 EXAMPLE","for instance","EXAMPLE","Identical to 'for example', and equally often a distractor.","Several metals resist corrosion in seawater. ___, titanium shows almost no pitting after a decade."),
("06 EXAMPLE","specifically","SPECIFICATION","Narrows from the general to the precise. Does NOT need a standalone example, only a sharper version of the same point. This is why it is credited far more often than 'for example'.","The decline was concentrated in one group. ___, it affected only birds that nest on the ground."),
("06 EXAMPLE","in particular","SPECIFICATION","Singles out one member of a group already mentioned.","All four reactors were modified. One, ___, received an entirely new cooling loop."),
("06 EXAMPLE","to be exact","SPECIFICATION","Supplies a precise figure for something just stated approximately.","The colony spans roughly a hectare. Forty-three hundred square meters, ___."),
("06 EXAMPLE","in many cases","SPECIFICATION","The general claim holds frequently but not universally.","Urban foxes shift their activity to the night. ___, they abandon daytime foraging entirely."),
("06 EXAMPLE","sometimes","SPECIFICATION","Signals occasional rather than consistent application of the prior claim.","The dye binds permanently to wool. ___, it washes out of cotton after a single rinse."),
("07 ADDITION","in addition","ADDITION","Adds a SEPARATE, equally weighted point. The new sentence must not be an example or a result.","The alloy is unusually light. ___, it can be machined without specialized tools."),
("07 ADDITION","additionally","ADDITION","Same as 'in addition'.","The grant covers equipment. ___, it funds two years of fieldwork."),
("07 ADDITION","moreover","ADDITION","Adds a point that ESCALATES the argument. The second point must be stronger, which it often is not.","The estimate rests on a single core sample. ___, that sample was collected before modern dating methods existed."),
("07 ADDITION","furthermore","ADDITION","Same escalating addition as 'moreover', and very rarely the credited answer.","The data were never published. ___, the original notebooks have since been lost."),
("07 ADDITION","besides","ADDITION","Informal addition. Almost never correct in the test's register.","The route is longer. ___, nobody has mapped the far side."),
("07 ADDITION","what's more","ADDITION","Informal escalating addition.","The device runs for a week on one charge. ___, it needs no calibration."),
("07 ADDITION","in the second place","SEQUENCE","Marks the second item in an enumerated list. Stilted and rarely correct.","First, the sample was contaminated. ___, the log was incomplete."),
("07 ADDITION","second of all","SEQUENCE","Informal list marker, outside the test's register.","First, the timing is wrong. ___, the cost is impossible."),
("08 SIMILARITY","similarly","SIMILARITY","Two situations share a PARALLEL structure. Requires genuine likeness, not mere relatedness. A very high-frequency distractor.","Coral bleaches when water warms past a threshold. ___, kelp forests collapse above a narrow temperature limit."),
("08 SIMILARITY","likewise","SIMILARITY","Same as 'similarly', and also mostly a distractor.","Northern populations migrate in early autumn. ___, the southern groups leave as soon as the rains end."),
("08 SIMILARITY","in comparison","COMPARISON","Sets two things against a shared measure.","The first engine burned four liters an hour. ___, the redesign uses barely one."),
("08 SIMILARITY","by comparison","COMPARISON","Same as 'in comparison', implying a measured difference.","The older telescope resolved features ten kilometers across. The new array, ___, resolves features under one."),
("08 SIMILARITY","fittingly","APTNESS","What follows is APPROPRIATE given what came before. Narrow use, but credited at a good rate when it appears.","She spent her career mapping the river's mouth. ___, the new survey vessel carries her name."),
("08 SIMILARITY","more often","FREQUENCY","Contrasts a more common case with a less common one.","Occasionally the fossils appear in pairs. ___, they are found as isolated fragments."),
("09 EMPHASIS","in fact","EMPHASIS","Confirms and then STRENGTHENS the prior claim, often surprisingly. One of the best-performing transitions on the test.","The technique is not new. ___, it appears in a manual printed in 1740."),
("09 EMPHASIS","indeed","EMPHASIS","Affirms and intensifies. The next sentence must go FURTHER, not merely agree.","The effect is easy to reproduce. ___, it appeared in every one of the ninety trials."),
("09 EMPHASIS","of course","EMPHASIS","Marks the point as obvious or already conceded.","___, no single study settles a question this large. The convergence across twelve of them is what matters."),
("09 EMPHASIS","actually","CORRECTION","Corrects a likely misconception. Informal, and needs a misconception to correct.","The pigment looks like ground lapis. It is, ___, a synthetic copper compound."),
("10 RESTATE","in other words","RESTATEMENT","The next sentence must say the SAME THING in different words and add NOTHING new. It appears constantly and is almost never right, because test sentences nearly always add information.","The species cannot survive outside this valley. ___, it is found nowhere else on Earth."),
("10 RESTATE","that is","RESTATEMENT","Clarifies or defines the prior statement. Same restriction: no new content.","The metal is ductile. ___, it can be drawn into wire without breaking."),
("11 SEQUENCE","first","SEQUENCE","Opens an ordered list of steps or points.","___, the sample is dried at low heat. Then it is weighed."),
("11 SEQUENCE","second","SEQUENCE","Marks the second item. Requires that a first was genuinely established.","First, the film is exposed. ___, it is developed in three baths."),
("11 SEQUENCE","next","SEQUENCE","The following step in a process or narrative.","The core is photographed and logged. ___, it is split lengthwise for sampling."),
("11 SEQUENCE","then","SEQUENCE","The immediately following event in time. Strong performer when the passage is a real chronology.","She mapped the eastern ridge in 1908. ___, she turned to the glacier itself."),
("11 SEQUENCE","finally","SEQUENCE","The LAST item in a genuine series.","The ore is crushed, then washed, then roasted. ___, it is cooled and graded."),
("11 SEQUENCE","subsequently","SEQUENCE","Happened after, with a sense of consequence in time.","The paper was rejected by two journals. It was ___ published, and widely cited."),
("11 SEQUENCE","afterward","SEQUENCE","Purely temporal: after that.","The building was gutted by fire in 1931. ___, only the facade was rebuilt."),
("11 SEQUENCE","later","SEQUENCE","At a subsequent time. Needs a clear earlier reference point.","He dismissed the idea in his first book. ___, he devoted three chapters to defending it."),
("11 SEQUENCE","eventually","SEQUENCE","After a long or uncertain interval.","The proposal sat unread for years. ___, a new director found it in a drawer."),
("11 SEQUENCE","soon","SEQUENCE","After a short interval.","The first colony was established in spring. ___, four more appeared along the same bank."),
("11 SEQUENCE","previously","SEQUENCE","Refers BACKWARD to an earlier time. The sentence must describe something before the main timeline.","The site is now dated to 9,000 years ago. ___, archaeologists had placed it in the Bronze Age."),
("11 SEQUENCE","earlier","SEQUENCE","Same backward reference as 'previously'.","The current map shows two channels. ___ surveys recorded only one."),
("11 SEQUENCE","meanwhile","SEQUENCE","Two things happening AT THE SAME TIME, often in different places.","The northern team drilled through the ice shelf. ___, a second crew surveyed the open water."),
("11 SEQUENCE","currently","SEQUENCE","Contrasts the present state with a past one.","The wetland once covered forty square kilometers. ___, it covers fewer than five."),
("11 SEQUENCE","nowadays","SEQUENCE","Present-day contrast with the past. Informal register.","Dyes were once extracted from shellfish. ___, nearly all are synthesized."),
("11 SEQUENCE","today","SEQUENCE","Marks the modern state of affairs against history.","The technique was a closely guarded secret for two centuries. ___, it is taught to undergraduates."),
("11 SEQUENCE","in the end","SEQUENCE","The final outcome after a process.","Three separate teams attempted the reconstruction. ___, the simplest model proved correct."),
("12 CONCLUSION","ultimately","CONCLUSION","States the FINAL upshot or most important consequence. A strong performer when a real outcome is being named.","The debate touched on funding, method and scope. ___, it came down to who owned the data."),
("12 CONCLUSION","in conclusion","SUMMARY","Signals the end of an entire argument. Test passages are excerpts, so this is never right.","___, the evidence supports the earlier date."),
("12 CONCLUSION","in summary","SUMMARY","Recaps everything preceding. Same problem: excerpts do not end.","___, three factors explain the decline."),
("12 CONCLUSION","in sum","SUMMARY","Formal recap, with the same problem.","___, the method is sound but the sample is too small."),
("12 CONCLUSION","to conclude","SUMMARY","Announces a closing, which an excerpt never does.","___, further fieldwork is needed."),
("12 CONCLUSION","lastly","SUMMARY","Final list item. Rarely correct; 'finally' is preferred.","___, the cost of transport must be considered."),
("12 CONCLUSION","firstly","SEQUENCE","Stilted variant of 'first', outside the test's register.","___, the timeline does not fit the geology."),
("12 CONCLUSION","secondly","SEQUENCE","Stilted variant of 'second', outside the test's register.","___, no second sample was ever collected."),
("13 PURPOSE","to that end","PURPOSE","Describes an ACTION TAKEN to achieve a goal just stated. Needs an explicit goal before it.","The city wanted to cool its streets by four degrees. ___, it planted twelve thousand trees."),
("13 PURPOSE","with this in mind","PURPOSE","Acts on the consideration just described.","Older cores may have been contaminated during storage. ___, the team re-sampled the entire site."),
("13 PURPOSE","in doing so","PURPOSE","The described action itself produced the following effect.","She rewrote the algorithm to use integers only. ___, she cut the runtime by half."),
("13 PURPOSE","in so doing","PURPOSE","Same as 'in doing so'.","He cataloged every variant spelling. ___, he revealed three distinct scribes."),
("13 PURPOSE","in response","PURPOSE","An action taken because of the prior event.","Readers objected to the missing citations. ___, the journal issued a corrected edition."),
("14 OTHER","there","PLACE","Refers to a location just named.","The expedition wintered on the eastern shore. ___, they recorded the lowest temperature of the year."),
("14 OTHER","elsewhere","PLACE","In a different location from the one just discussed.","In Norway the practice died out by 1900. ___, it survived another fifty years."),
("14 OTHER","in reality","CORRECTION","Corrects an expectation or misconception with the true state.","The engraving appears to show a harbor. ___, it depicts a flooded quarry."),
("14 OTHER","again and again","FREQUENCY","Emphasizes repetition.","The pattern is not a coincidence. It appears ___ across every layer of the deposit."),
("14 OTHER","intermittently","FREQUENCY","Happening at irregular intervals.","The spring does not flow steadily. It runs ___, usually after heavy rain."),
("14 OTHER","increasingly","DEGREE","A trend growing over time.","Early models ignored cloud cover. Later ones relied on it ___."),
("14 OTHER","alternately","ALTERNATION","Switching back and forth between two states. Do not confuse with 'alternatively', which offers an option.","The valve does not hold one position. It opens and closes ___, once per second."),
]
