# -*- coding: utf-8 -*-
# B: near-synonym discrimination (the hardest words-in-context skill)
B = [
("ambiguous vs ambivalent","AMBIGUOUS describes a THING with more than one possible meaning. AMBIVALENT describes a PERSON with mixed feelings. | The ending is ambiguous; the reader is ambivalent. | Never say 'he was ambiguous about the offer'."),
("imply vs infer","The speaker or text IMPLIES; the reader or listener INFERS. | Authors imply, you infer. | SAT loves this in 'what can be inferred' versus 'the author implies'."),
("substantiate vs corroborate","SUBSTANTIATE means to supply evidence for a claim that had none. CORROBORATE means to ADD confirming evidence to something already claimed by another source. | You substantiate your own claim; a second study corroborates the first."),
("refute vs rebut vs repudiate","REFUTE means to actually PROVE false. REBUT means to argue against without necessarily proving. REPUDIATE means to disown or reject, often your own earlier view. | A rebuttal may fail; a refutation succeeds by definition."),
("skeptical vs cynical","SKEPTICAL means withholding belief pending evidence, which is a neutral scientific stance. CYNICAL means assuming bad motives. | Reviewers were skeptical of the data, not cynical about it."),
("nuance vs ambiguity","NUANCE is a subtle distinction that ADDS precision. AMBIGUITY is a lack of clarity that SUBTRACTS it. | Nuance is a virtue; ambiguity is usually a flaw."),
("explicit vs implicit","EXPLICIT is stated outright. IMPLICIT is present but unstated. | If the text says it, it is explicit; if you must supply it, it is implicit."),
("tangential vs peripheral","TANGENTIAL means only glancingly RELATED to the topic. PERIPHERAL means of minor IMPORTANCE, possibly still on-topic. | A tangential point wanders; a peripheral point is just small."),
("pragmatic vs expedient","PRAGMATIC is practical and is a compliment. EXPEDIENT is convenient at the cost of principle and is a criticism. | Watch the connotation; the SAT tests it."),
("undermine vs refute","UNDERMINE means to WEAKEN gradually. REFUTE means to DEFEAT outright. | New data can undermine a theory long before anything refutes it."),
("concede vs condone","CONCEDE means to admit a point. CONDONE means to approve of or overlook wrongdoing. | She conceded the error; she did not condone it."),
("affect vs effect","AFFECT is almost always the VERB (to influence). EFFECT is almost always the NOUN (the result). | Rare exception: 'to effect change' means to bring it about."),
("comprise vs compose","The WHOLE comprises the parts; the PARTS compose the whole. | The archive comprises letters. The letters compose the archive. | 'Is comprised of' is the classic error."),
("prescribe vs proscribe","PRESCRIBE means to recommend or order. PROSCRIBE means to FORBID. | Near-opposites separated by two letters, which is exactly why it appears."),
("discrete vs discreet","DISCRETE means separate and distinct. DISCREET means tactful and private. | Three discrete categories; a discreet inquiry."),
("eminent vs imminent vs immanent","EMINENT means distinguished. IMMINENT means about to happen. IMMANENT means inherent throughout. | An eminent scholar warned of imminent collapse."),
("elicit vs illicit","ELICIT is a VERB meaning to draw out. ILLICIT is an ADJECTIVE meaning illegal. | The question elicited an account of illicit trade."),
("credible vs credulous vs creditable","CREDIBLE means believable. CREDULOUS means too willing to believe. CREDITABLE means deserving praise. | A credible witness, a credulous audience, a creditable effort."),
("disinterested vs uninterested","DISINTERESTED means impartial, having no stake. UNINTERESTED means bored. | You want a disinterested judge, not an uninterested one."),
("enervate vs invigorate","ENERVATE means to DRAIN of energy, despite sounding energetic. INVIGORATE means to energize. | The sound of the word points the wrong way, which is the trap."),
("fortuitous vs fortunate","FORTUITOUS means happening by CHANCE (neutral). FORTUNATE means LUCKY (positive). | A fortuitous meeting may be unwelcome."),
("noisome vs noisy","NOISOME means foul-smelling or harmful, nothing to do with sound. | Another word whose sound misleads."),
("venal vs venial","VENAL means corruptible by bribery. VENIAL means minor and forgivable. | Nearly opposite in severity."),
("appraise vs apprise","APPRAISE means to assess value. APPRISE means to inform. | He appraised the collection, then apprised the owner."),
("censure vs censor","CENSURE means to formally criticize. CENSOR means to suppress content. | The board censured him; it did not censor him."),
("flout vs flaunt","FLOUT means to openly disregard a rule. FLAUNT means to display showily. | They flouted the ban while flaunting their wealth."),
("principle vs principal","PRINCIPLE is a NOUN meaning a rule or belief. PRINCIPAL means chief, or the head of a school, or an original sum. | A matter of principle; the principal reason."),
]
# C: second meanings - common words used in uncommon senses (a core digital SAT pattern)
C = [
("qualify (second meaning)","Usual: to be eligible. SAT SENSE: to LIMIT or soften a claim. | 'The author qualifies her argument' means she adds a restriction, not that she becomes eligible."),
("yield (second meaning)","Usual: to give way. SAT SENSE: to PRODUCE as a result. | 'The experiment yielded three findings' means it produced them."),
("render (second meaning)","Usual: to depict. SAT SENSE: to CAUSE TO BECOME. | 'Rendered the method obsolete' means made it obsolete."),
("sanction (two opposite meanings)","Can mean to APPROVE officially, or a PENALTY imposed. | 'The state sanctioned the practice' = permitted it. 'Sanctions against the state' = punishments. Context decides; this is the trickiest word on the list."),
("novel (second meaning)","Usual: a book. SAT SENSE (adjective): NEW and original. | 'A novel approach' has nothing to do with fiction."),
("table (second meaning)","Usual: a chart or furniture. SAT SENSE: to POSTPONE discussion of. | 'The motion was tabled' means set aside."),
("arrest (second meaning)","Usual: to detain. SAT SENSE: to STOP or halt. | 'Arrested development' means halted growth."),
("check (second meaning)","Usual: to verify. SAT SENSE: to RESTRAIN or hold back. | 'A check on executive power' means a limit."),
("temper (second meaning)","Usual: mood. SAT SENSE: to MODERATE or soften. | 'Tempered by experience' means made less extreme."),
("compound (second meaning)","Usual: a mixture. SAT SENSE: to MAKE WORSE or increase. | 'Compounded the problem' means intensified it."),
("hedge (second meaning)","Usual: a bush. SAT SENSE: to avoid committing to a position. | 'The author hedges' means she avoids a firm claim."),
("foil (second meaning)","Usual: metal wrap. SAT SENSES: to THWART a plan, or a CHARACTER who contrasts with another. | Both appear on the SAT; literature passages use the second."),
("bank (second meaning)","Usual: a financial institution. SAT SENSES: the side of a river, or to RELY ON. | 'Banking on a result' means counting on it."),
("spike (second meaning)","Usual: a sharp point. SAT SENSE: a sudden sharp INCREASE. | 'A spike in temperature' is the graph sense."),
("stream (second meaning)","Usual: a small river. SAT SENSE: a continuous FLOW of anything. | 'A steady stream of objections.'"),
("delegate (second meaning)","As a VERB: to ASSIGN a task to someone else. As a NOUN: a representative. | Stress shifts between the two; the verb sense is the tested one."),
("economy (second meaning)","Usual: a financial system. SAT SENSE: efficiency, doing much with little. | 'Economy of expression' means concise writing."),
("appreciate (second meaning)","Usual: to be grateful. SAT SENSES: to UNDERSTAND fully, or to INCREASE in value. | 'To appreciate the difficulty' means to grasp it."),
("observe (second meaning)","Usual: to watch. SAT SENSES: to REMARK, or to COMPLY WITH a rule. | 'As the author observes' means as she remarks."),
("sound (second meaning)","Usual: noise. SAT SENSE (adjective): VALID, well-founded. | 'A sound argument' has no auditory meaning."),
("plastic (second meaning)","Usual: a material. SAT SENSE: capable of being SHAPED, malleable. | 'Plastic behavior' means adaptable."),
("mint (second meaning)","Usual: a plant or candy. SAT SENSES: to COIN money, or 'in mint condition' meaning pristine. | Also 'to mint a term' = to invent it."),
("relative (second meaning)","Usual: a family member. SAT SENSE (adjective): considered in COMPARISON, not absolute. | 'Relative scarcity' means scarce compared to something."),
("discriminate (second meaning)","Usual: to treat unfairly. SAT SENSE: to DISTINGUISH carefully between things. | 'A discriminating ear' is a compliment."),
("exhaust (second meaning)","Usual: to tire out. SAT SENSE: to USE UP completely, or to treat a topic fully. | 'Exhausted the possibilities' means covered them all."),
]
