# -*- coding: utf-8 -*-
# A: harder single words
A = [
("abate","(v.) to lessen in intensity. The storm abated by midnight."),
("abhor","(v.) to regard with disgust. She abhorred the practice and said so publicly."),
("acerbic","(adj.) sharp and biting in tone. His acerbic review ended the playwright's season."),
("acumen","(n.) keen practical judgment. Her business acumen saved the press."),
("admonish","(v.) to warn or reprove gently. The editor admonished him for missing the deadline."),
("affable","(adj.) easy to talk to; friendly. An affable guide made the tour bearable."),
("alleviate","(v.) to make suffering less severe. Shade alleviated the worst of the heat."),
("antipathy","(n.) deep-seated dislike. There was open antipathy between the two schools."),
("aversion","(n.) a strong dislike or avoidance. He had an aversion to public speaking."),
("belittle","(v.) to make seem unimportant. Do not belittle work you have not attempted."),
("belligerent","(adj.) hostile and aggressive. The belligerent tone derailed the hearing."),
("bombastic","(adj.) high-sounding but with little meaning. The speech was bombastic and forgettable."),
("brevity","(n.) shortness of expression. The letter's brevity was itself the message."),
("brusque","(adj.) abrupt to the point of rudeness. Her brusque reply ended the exchange."),
("callous","(adj.) emotionally hardened; unfeeling. The policy was callous in its indifference."),
("candor","(n.) frankness; honest directness. His candor cost him the appointment."),
("capricious","(adj.) given to sudden unpredictable changes. Capricious weather ruined the survey."),
("castigate","(v.) to reprimand severely. Reviewers castigated the study's methods."),
("censure","(v.) to criticize formally. The society censured two of its own members."),
("circumspect","(adj.) cautious; considering all consequences. She was circumspect in every public statement."),
("conscientious","(adj.) diligent and careful about duty. A conscientious assistant caught the error."),
("dearth","(n.) a scarcity. There is a dearth of reliable data before 1890."),
("deride","(v.) to mock or ridicule. Critics derided the theory for a decade."),
("desolate","(adj.) bleak and empty. The desolate plateau supports almost nothing."),
("dubious","(adj.) doubtful; questionable. The provenance of the manuscript is dubious."),
("eclectic","(adj.) drawing from many sources. Her eclectic method borrowed from three disciplines."),
("egalitarian","(adj.) favoring equality. The charter was unusually egalitarian for its time."),
("eminent","(adj.) distinguished; notable. An eminent geologist reviewed the claim."),
("enigma","(n.) something puzzling or mysterious. The inscription remains an enigma."),
("expedient","(adj.) convenient though perhaps improper. It was expedient rather than principled."),
("extricate","(v.) to free from a difficulty. She extricated the project from its funding mess."),
("fathom","(v.) to understand after effort. No one could fathom the gap in the record."),
("fervor","(n.) intense passion. He argued with a fervor the topic rarely inspires."),
("fickle","(adj.) changing loyalties or opinions often. Public taste is fickle."),
("flagrant","(adj.) conspicuously offensive. A flagrant violation of the protocol."),
("flout","(v.) to openly disregard a rule. They flouted the ban for years."),
("frugal","(adj.) economical; sparing. A frugal design used half the material."),
("garrulous","(adj.) excessively talkative. A garrulous witness buried the key detail."),
("germane","(adj.) relevant to the matter. That objection is not germane."),
("gregarious","(adj.) sociable; fond of company. Gregarious birds nest in dense colonies."),
("guile","(n.) cunning deceit. He secured the contract by guile."),
("gullible","(adj.) easily deceived. The scheme preyed on gullible investors."),
("haughty","(adj.) arrogantly superior. A haughty dismissal of the criticism."),
("iconoclast","(n.) one who attacks cherished beliefs. She was an iconoclast in a conservative field."),
("immutable","(adj.) unchanging. The constant is immutable across every trial."),
("impulsive","(adj.) acting without forethought. An impulsive edit weakened the chapter."),
("incisive","(adj.) sharply analytical. An incisive reading of the data."),
("incongruity","(n.) a lack of harmony or fit. The incongruity between claim and evidence is glaring."),
("incredulous","(adj.) unwilling to believe. She was incredulous at the reported figure."),
("indelible","(adj.) impossible to remove. The episode left an indelible mark."),
("indignant","(adj.) angry at unfair treatment. An indignant letter followed the rejection."),
("inert","(adj.) inactive; without power to move. The gas is chemically inert."),
("insidious","(adj.) harmful in a gradual, hidden way. The insidious spread went unnoticed."),
("intermittent","(adj.) occurring at irregular intervals. Intermittent signals frustrated the survey."),
("intrinsic","(adj.) belonging naturally; essential. Curiosity is intrinsic to the work."),
("inundate","(v.) to flood or overwhelm. The office was inundated with responses."),
("irreverent","(adj.) lacking due respect. An irreverent footnote enlivened the monograph."),
("lament","(v.) to mourn or express regret. He lamented the loss of the archive."),
("languid","(adj.) lacking energy; slow. A languid afternoon in the reading room."),
("magnanimous","(adj.) generous, especially toward a rival. A magnanimous concession speech."),
("malleable","(adj.) easily shaped; adaptable. Gold is malleable enough to be beaten into leaf."),
("mundane","(adj.) ordinary; dull. The cause turned out to be mundane."),
("notoriety","(n.) fame for something bad. The case brought unwelcome notoriety."),
("oblivious","(adj.) unaware. He was oblivious to the change in tone."),
("obstinate","(adj.) stubbornly refusing to change. An obstinate refusal to revise."),
("ominous","(adj.) suggesting something bad will happen. An ominous drop in pressure."),
("onerous","(adj.) burdensome. The reporting requirements are onerous."),
("opulent","(adj.) luxurious; lavish. An opulent binding on a modest text."),
("ostracize","(v.) to exclude from a group. She was ostracized for the dissent."),
("palliate","(v.) to make less severe without curing. The measure palliated but did not solve."),
("paltry","(adj.) meagre; contemptibly small. A paltry sum for two years of work."),
("pensive","(adj.) deeply thoughtful, often sadly. A pensive final chapter."),
("perfunctory","(adj.) done routinely with little care. A perfunctory review missed the flaw."),
("permeate","(v.) to spread throughout. The idea permeated the whole discipline."),
("pertinent","(adj.) relevant. Only two of the objections are pertinent."),
("petulant","(adj.) childishly sulky or irritable. A petulant response to fair criticism."),
("placate","(v.) to soothe or appease. Nothing placated the committee."),
("placid","(adj.) calm and untroubled. A placid surface over a fast current."),
("plight","(n.) a difficult situation. The plight of the coastal villages worsened."),
("precedent","(n.) an earlier case used as a guide. There is no precedent for this ruling."),
("predilection","(n.) a preference or liking. A predilection for long sentences."),
("preeminent","(adj.) surpassing all others. The preeminent authority on the period."),
("premise","(n.) a proposition supporting a conclusion. The premise is never defended."),
("presumptuous","(adj.) overstepping what is appropriate. It seemed presumptuous to revise her notes."),
("pretense","(n.) a false show or claim. He dropped the pretense of neutrality."),
("prevalent","(adj.) widespread. The practice was prevalent by 1900."),
("prodigious","(adj.) remarkably great. A prodigious output over forty years."),
("promulgate","(v.) to make widely known; to proclaim. The rule was promulgated in spring."),
("pungent","(adj.) sharp in smell or taste; biting. A pungent aside in the preface."),
("quandary","(n.) a state of uncertainty. The finding left her in a quandary."),
("quibble","(v.) to argue over trivia. Do not quibble about the footnotes."),
("quiescent","(adj.) inactive or dormant. The system stayed quiescent for a decade."),
("rarefied","(adj.) belonging to a small elite; thin (of air). The rarefied world of manuscript collecting."),
("rebuff","(v.) to reject bluntly. The offer was rebuffed twice."),
("rebuttal","(n.) a counterargument. Her rebuttal ran to thirty pages."),
("recluse","(n.) one who lives in isolation. He became a recluse after 1912."),
("relish","(v.) to enjoy greatly. She relished the argument more than the result."),
("renege","(v.) to go back on a promise. The publisher reneged on the advance."),
("reprehensible","(adj.) deserving condemnation. The omission was reprehensible."),
("reproach","(v.) to express disapproval. He reproached himself for the delay."),
("resolute","(adj.) firmly determined. A resolute defense of the method."),
("retribution","(n.) punishment inflicted in return. They feared retribution for the report."),
("rigorous","(adj.) extremely thorough or strict. A rigorous re-analysis confirmed it."),
("ruthless","(adj.) without pity. Ruthless editing improved the book."),
("sagacious","(adj.) having keen judgment. A sagacious choice of collaborators."),
("sardonic","(adj.) grimly mocking. A sardonic footnote about his rivals."),
("scant","(adj.) barely sufficient. Scant evidence supports the earlier date."),
("scathing","(adj.) severely critical. A scathing assessment of the design."),
("slander","(n.) a false spoken statement damaging reputation. The accusation was pure slander."),
("somber","(adj.) dark and gloomy; grave. A somber palette throughout."),
("sordid","(adj.) morally degraded; squalid. The sordid details were left out."),
("specious","(adj.) superficially plausible but wrong. A specious argument that fooled reviewers."),
("sporadic","(adj.) occurring irregularly. Sporadic reports over two centuries."),
("staid","(adj.) sedate and conventional. A staid journal published the radical paper."),
("stalwart","(adj.) loyal and dependable. A stalwart supporter of the program."),
("stigma","(n.) a mark of disgrace. The stigma outlasted the ruling."),
("stoic","(adj.) enduring hardship without complaint. A stoic acceptance of the verdict."),
("stringent","(adj.) strict and demanding. Stringent controls on the sample."),
("sublime","(adj.) of outstanding beauty or grandeur. A sublime passage in the third movement."),
("subside","(v.) to become less intense; to sink. The swelling subsided overnight."),
("sycophant","(n.) a flatterer seeking advantage. The court was full of sycophants."),
("taint","(v.) to contaminate. One bad sample tainted the whole run."),
("tepid","(adj.) lukewarm; unenthusiastic. A tepid response from the field."),
("tirade","(n.) a long angry speech. The tirade lasted twenty minutes."),
("tortuous","(adj.) full of twists; complex. A tortuous chain of reasoning."),
("transgress","(v.) to violate a rule or boundary. The study transgressed its own protocol."),
("trenchant","(adj.) vigorous and incisive. A trenchant critique of the model."),
("trite","(adj.) overused and unoriginal. The metaphor is trite."),
("turmoil","(n.) a state of great disturbance. The field was in turmoil for years."),
("unkempt","(adj.) untidy. Unkempt notes made the reconstruction hard."),
("unnerve","(v.) to deprive of courage. The result unnerved the whole team."),
("unwieldy","(adj.) awkward to handle because of size. An unwieldy dataset."),
("upbraid","(v.) to scold sharply. She upbraided them for the oversight."),
("urbane","(adj.) suave and sophisticated. An urbane and evasive reply."),
("usurp","(v.) to seize power wrongfully. The board usurped the director's role."),
("vapid","(adj.) offering nothing stimulating. A vapid introduction to a strong book."),
("venerate","(v.) to regard with deep respect. The site is venerated locally."),
("verbose","(adj.) using more words than needed. The report is verbose but accurate."),
("vigilant","(adj.) watchful for danger. Vigilant monitoring caught the leak."),
("viscous","(adj.) thick and sticky. A viscous residue coated the vessel."),
("wary","(adj.) cautious of danger. She was wary of the single-source claim."),
("whimsical","(adj.) playfully odd. A whimsical index closes the volume."),
("wry","(adj.) dryly humorous. A wry observation about peer review."),
("zeal","(n.) great energy for a cause. He pursued it with missionary zeal."),
("zenith","(n.) the highest point. The movement reached its zenith in 1925."),
]
